/**
 * User Data Model Module — In-Memory User Store
 *
 * Provides the data access layer for user management in the authentication system.
 * Implements an in-memory data store backed by a JavaScript array, designed for
 * easy replacement with a persistent database ORM (Sequelize, Prisma, Knex) in
 * production environments without changing the calling code interface.
 *
 * Features:
 * - User creation with auto-generated UUID identifiers and ISO 8601 timestamps
 * - Lookup by email address (returns full record including password hash for auth verification)
 * - Lookup by user ID (returns sanitized record excluding password hash)
 * - Security-conscious API: hashedPassword is stripped from all public-facing return values
 *   except where explicitly needed for password verification during login
 *
 * User Object Schema:
 * {
 *   id: string,             // UUID v4 generated via crypto.randomUUID()
 *   username: string,       // User display name (3+ characters, trimmed and escaped)
 *   email: string,          // Normalized email address (lowercase, trimmed)
 *   hashedPassword: string, // bcrypt hash string (generated by controller layer)
 *   createdAt: string       // ISO 8601 date string (e.g., '2025-01-01T00:00:00.000Z')
 * }
 *
 * Security Considerations:
 * - The hashedPassword field is NEVER returned in API responses except via findByEmail(),
 *   which is used exclusively by the auth controller for bcrypt.compare() during login.
 * - create() and findById() always return sanitized copies with hashedPassword removed.
 * - The model does not generate user-facing error messages; null returns enable the
 *   controller to provide opaque "Invalid credentials" responses without revealing
 *   whether an email address exists in the system.
 *
 * Integration:
 *   const User = require('../models/user');
 *   const newUser = User.create({ username, email, hashedPassword });
 *   const existingUser = User.findByEmail('user@example.com');
 *   const userProfile = User.findById('uuid-string');
 *
 * @module models/user
 * @requires crypto — Node.js built-in cryptographic module for UUID generation
 */

'use strict';

const crypto = require('crypto');

/**
 * In-Memory User Data Store
 *
 * Module-scoped array serving as the database backing store for user records.
 * This array is private and only accessible through the exported methods
 * (create, findByEmail, findById). Each element is a complete user object
 * conforming to the User Object Schema documented above.
 *
 * In production, this array will be replaced with database table queries
 * (e.g., a 'users' table in PostgreSQL via Sequelize or Prisma ORM).
 *
 * @type {Array<Object>}
 * @private
 */
const users = [];

/**
 * Create a New User Record
 *
 * Generates a new user object with an auto-generated UUID and ISO 8601 timestamp,
 * stores it in the in-memory data store, and returns a sanitized copy of the user
 * with the hashedPassword field removed for safe inclusion in API responses.
 *
 * The password is expected to be ALREADY hashed by the controller layer using
 * bcryptjs before being passed to this method. This model never handles plain-text
 * passwords directly.
 *
 * Usage Example:
 *   const User = require('../models/user');
 *   const bcrypt = require('bcryptjs');
 *
 *   const hashedPassword = await bcrypt.hash(plainPassword, 10);
 *   const newUser = User.create({ username: 'john_doe', email: 'john@example.com', hashedPassword });
 *   // Returns: { id: 'uuid', username: 'john_doe', email: 'john@example.com', createdAt: '...' }
 *   // Note: hashedPassword is NOT included in the return value
 *
 * @function create
 * @param {Object} userData - The user data to persist
 * @param {string} userData.username - User display name (3+ characters, pre-validated)
 * @param {string} userData.email - Normalized email address (pre-validated by express-validator)
 * @param {string} userData.hashedPassword - bcrypt hash of the user's password (hashed by controller)
 * @returns {Object} Sanitized user object: { id: string, username: string, email: string, createdAt: string }
 */
const create = (userData) => {
  // Generate a cryptographically secure UUID v4 identifier for the new user
  const id = crypto.randomUUID();

  // Create an ISO 8601 timestamp for the record creation time
  const createdAt = new Date().toISOString();

  // Build the complete user object with all required fields
  const newUser = {
    id,
    username: userData.username,
    email: userData.email,
    hashedPassword: userData.hashedPassword,
    createdAt
  };

  // Persist the user record in the in-memory data store
  users.push(newUser);

  // Return a sanitized copy with hashedPassword excluded for API response safety
  // Destructuring extracts hashedPassword separately; the rest operator collects safe fields
  const { hashedPassword, ...safeUser } = newUser;
  return safeUser;
};

/**
 * Find a User by Email Address
 *
 * Searches the in-memory data store for a user record matching the provided email.
 * Returns the FULL user object INCLUDING the hashedPassword field if found, or null
 * if no matching record exists.
 *
 * SECURITY NOTE: This method intentionally returns the hashedPassword field because
 * it is required by the auth controller to perform bcrypt.compare() during the login
 * flow. The controller is responsible for NEVER exposing the hashedPassword field to
 * the client in API responses. Only the controller layer should call this method.
 *
 * This null-return pattern enables the controller to provide opaque error messages
 * (e.g., "Invalid credentials") without revealing whether the email exists in the
 * system, preventing user enumeration attacks.
 *
 * Usage Example:
 *   const User = require('../models/user');
 *   const user = User.findByEmail('john@example.com');
 *   if (!user) {
 *     return res.status(401).json({ message: 'Invalid credentials' });
 *   }
 *   const isMatch = await bcrypt.compare(password, user.hashedPassword);
 *
 * @function findByEmail
 * @param {string} email - The email address to search for (case-sensitive match)
 * @returns {Object|null} Full user object including hashedPassword if found, or null if not found
 */
const findByEmail = (email) => {
  // Search the users array for a record with a matching email address
  const foundUser = users.find((user) => user.email === email);

  // Return the found user or explicitly return null (not undefined) for consistent API
  return foundUser || null;
};

/**
 * Find a User by UUID Identifier
 *
 * Searches the in-memory data store for a user record matching the provided UUID.
 * Returns a SANITIZED copy of the user object with the hashedPassword field removed
 * if found, or null if no matching record exists.
 *
 * Unlike findByEmail(), this method strips the hashedPassword from the returned
 * object because it is used for profile retrieval and general user lookups where
 * the password hash is not needed and should not be exposed.
 *
 * Usage Example:
 *   const User = require('../models/user');
 *   const userProfile = User.findById(req.user.id);
 *   if (!userProfile) {
 *     return res.status(404).json({ message: 'User not found' });
 *   }
 *   res.json({ user: userProfile });
 *
 * @function findById
 * @param {string} id - The UUID to search for
 * @returns {Object|null} Sanitized user object (without hashedPassword) if found, or null if not found
 */
const findById = (id) => {
  // Search the users array for a record with a matching UUID
  const user = users.find((user) => user.id === id);

  // If no user found, return null explicitly
  if (!user) {
    return null;
  }

  // Destructure to exclude hashedPassword, returning only safe fields
  const { hashedPassword, ...safeUser } = user;
  return safeUser;
};

/**
 * Module Exports
 *
 * Exports three data access methods for the User model:
 * 1. create      — Create a new user record and return sanitized copy (no hashedPassword)
 * 2. findByEmail — Look up user by email, returns full record WITH hashedPassword (for login)
 * 3. findById    — Look up user by UUID, returns sanitized record (no hashedPassword)
 *
 * Integration Example:
 *   const User = require('../models/user');
 *   const newUser = User.create({ username, email, hashedPassword });
 *   const loginUser = User.findByEmail(email);     // includes hashedPassword
 *   const profile = User.findById(userId);          // excludes hashedPassword
 *
 * Future Database Migration:
 *   Replace this module's implementation with database ORM queries (e.g., Sequelize,
 *   Prisma) while preserving the same exported function signatures to maintain
 *   backward compatibility with controllers and routes.
 */
module.exports = {
  create,
  findByEmail,
  findById
};
